#pragma once
#include "ast/ast.hpp"
#include <sys/cdefs.h>
#include <optional>
#include "symtable/symtable.hpp"
namespace LIRA {
namespace MIR{
class LocalDestRegister{
    std::string dest_register_name;
    IR::TypeExprPtr type;//Type of the register.

    bool artificial;//Generated by our user compiler and not present in the original code
    bool synthetic;//Generated by us in the middle of the compilation process and not present in the original code. 
    // This is different from artificial because artificial means it is generated by our user compiler and not present in the original code but 
    // synthetic means it is generated by us in the middle of the compilation process and not present in the original code. 
    bool nonnull;
    bool nopoison;
    bool nnan;
    bool ninf;
    bool noalias;
    std::string scope;//Empty if not set. Name of the scope variable in it. Used to define in what scope this register belongs to in the original user language. Set by the #[scope(scope:^scope_name)]
    std::string original_name;//Empty if not set. Name of the original variable(from user's language) that this register represents. Set by the #[name(str:"var name")]
    std::size_t dereferenceable_bytes; //If 0 means the value is not set
    std::size_t alignment;
    public:
    LocalDestRegister(std::string dest_register_name, IR::TypeExprPtr type,bool artificial, bool synthetic, bool nonnull, bool nopoison, bool nnan, bool ninf, 
                      bool noalias, std::string original_name, std::string scope, std::size_t dereferenceable_bytes, std::size_t alignment);
    void change_type(IR::TypeExprPtr new_type);//SHould be used only in rare cases like when the type is set to str but now we know the length of the string and we want to change the type to [i8,N] where N is the length of the string.  

    std::string get_dest_register_name() const;
    IR::TypeExprPtr get_type() const;

    bool is_artificial() const;
    bool is_synthetic() const;
    bool is_nonnull() const;
    bool is_nopoison() const;
    bool is_nnan() const;
    bool is_ninf() const;
    bool is_noalias() const;
    
    std::string get_original_name() const;
    std::string get_scope() const;
    std::size_t get_dereferenceable_bytes() const;
    std::size_t get_alignment() const;

    std::string to_string() const;
};

using LocalDestRegisterPtr = std::shared_ptr<LocalDestRegister>;

class GlobalDestRegister{
    //TODO: This class should also store the innitial value if given + sometimes the inntial value may be ptr to another global variable. Do it in future
    // https://claude.ai/share/581b2c91-6551-49ca-8a66-0748123491f2
    // https://claude.ai/share/b162a4ea-14ea-440b-ac89-dee4eac4f1b6
};
}
}